### ISSUE TITLE
Refresh token method seems to be missing

### ISSUE THREAD

**Issue by ghost** [CodeMazeBlog/blazor-series#2]
Hi,

at first, thanks for your effort!

I downloaded the repository and as I see you configured the token with a 5 min expiration. But there seems to be no token refresh method implemented. After 5 minutes you get a 401:
```

Request URL: https://localhost:5011/api/products?pageNumber=3&searchTerm=&orderBy=name
Request Method: GET
Status Code: 401 
Remote Address: [::1]:5011
Referrer Policy: no-referrer-when-downgrade
access-control-allow-origin: *
access-control-expose-headers: X-Pagination
content-length: 0
date: Mon, 07 Sep 2020 12:04:13 GMT
server: Kestrel
status: 401
www-authenticate: Bearer error="invalid_token", error_description="The token expired at '09/07/2020 11:49:07'"
```

This seems to be a common issue regarding JWT tutorials, to not consider the refreshing of the token ;-)

As I am new to Blazor this would be very helpful. Had lots of trouble alreadý with refreshing tokens in Angular und Web API in the past.

Best regards,
Kay

**Comment by MarinkoSpasojevic** [comment]
Hi Kay. 

I wouldn't say this is an issue because we didn't implement the refresh token at all. 

But if you want to learn more about it, please read our article on this topic: https://code-maze.com/using-refresh-tokens-in-asp-net-core-authentication/

It uses the web API with JWT and Angular, but the principle is the same.
